# Logs centralisés simple (remote-safe)
# SRV-LAN-A 192.168.50.10 = collecteur rsyslog. pfSense A+B envoient en syslog distant.

## Sur Ubuntu collecteur (SRV-LAN-A)
# sudo apt install -y rsyslog
# copier 50-pfsense.conf vers /etc/rsyslog.d/ puis systemctl restart rsyslog
# sudo mkdir -p /var/log/pfsense && sudo chown syslog:adm /var/log/pfsense
# tail -f /var/log/pfsense/pfsense.log  (à montrer en vidéo)

module(load="imudp") input(type="imudp" port="514" ruleset="pfsense")
module(load="imtcp") input(type="imtcp" port="514" ruleset="pfsense")
ruleset(name="pfsense") {
  action(type="omfile" file="/var/log/pfsense/pfsense.log")
  stop
}
